### ISSUE TITLE
Use `with`?

### ISSUE THREAD

**Issue by wesleytodd** [Drulac/template-literal#1]
Typically I wouldn't ever recommend using `with`, but in this case it seems like it would improve the api of this module to switch to something like this:

```javascript
module.exports = (templateStr) => return new Function('d', 'with (d) { return `' + templateStr + '` }');
```

The performance hit is pretty minimal (see below), and it does not force users to have that `d.` strewn through their templates.  What do you think?  Or is the performance aspect the main focus of this package?

Here is the perf test I did:

```
$ cat template-literal.js
var tmplWith = (str) => new Function('d', 'with (d) { return `' + str + '` }');
var tmplWithout = (str) => return new Function('d', 'return `' + str + '`');

var time = (fnc) => {
  console.time(fnc.name);
  for (let i = 0; i < 10000; i++) fnc.call(null, i);
  console.timeEnd(fnc.name);
};
time(function runWith (i) {
	tmplWith('i: ${i}')({ i });
});
time(function runWithout (i) {
	tmplWithout('i: ${d.i}')({ i });
});

$ node template-literal.js
node template-literal.js
runWith: 16.748ms
runWithout: 11.198ms
```

**Comment by Drulac** [comment]
That have a little performance impact on compilation, but the impact is huge on running : 
```
With : Literal render x 455,629 ops/sec ±0.20% (84 runs sampled)
Without : Literal render x 3,278,679 ops/sec ±0.44% (81 runs sampled) 
```

It became 7 times more long... It's a good improvement, I think the performance loss is to high to add it.

(In the [bench/](bench/) directory there is [compile.js](bench/compile.js) who is perfect to benchmark, you can comment other  frameworks' tests to win time)

**Comment by wesleytodd** [comment]
Ok, so performance is your biggest concern for this module then.  That is why I asked, because it is obviously slower to use `with`.  My very minimal test did not show such poor performance as yours did or I wouldn't have even brought it up.  The performance hit probably scales with the number of variable lookup's.

Anyway, I just thought it was worth bringing up because the hard coded `d` variable for access inside the templates seemed less user friendly than the `with` version.

**Comment by Drulac** [comment]
You have only tested template compilation, who run one time in an application, I have run template rendering, who run at each page load ;-)

Yes I know it may be not friendly at first use, but the performance decrease is too high to add it :-/

**Comment by Drulac** [comment]
But I can add an option to choose the name of the variable, with `d` as default value ?

**Comment by wesleytodd** [comment]
I tested compilation and rendering in one go.  I agree that is not technically accurate to a use case, it was just my 2 second look at what the perf difference would be.  I probably wont be using the module anyway, just thought I would give my feedback since you posted over on the express repo.  But I do think that adding the option to change the variable name might help with other people wanting to use this, again just my 2c.

**Comment by Drulac** [comment]
Thanks for you feedback :-)

I'm french, and not really good at english, I  havn't understand "again just my 2c" 😅

**Comment by wesleytodd** [comment]
Haha, no worries.  "just my 2c" is an English saying which means "I am giving my personal opinion".  See https://en.wikipedia.org/wiki/My_two_cents

**Comment by Drulac** [comment]
Oh ok thanks for explainations :-)
